version: "3.8"

services:
  scum-server:
    image: cxsorious/scum-unraid-server:latest
    container_name: scum-server
    environment:
      - SCUM_PORT=7777
      - SCUM_MAX_PLAYERS=128
      - SCUM_NO_BATTLEYE=false
      - VALIDATE=false
      - STEAM_APP_ID=3792580
      - WINEPREFIX=/wineprefix
      - SERVER_DIR=/serverdata/SCUM
      - BACKUP_DIR=/serverdata/backups
      - STEAMCMD_DIR=/serverdata/steamcmd
      - PUID=99
      - PGID=100
      - UMASK=000
    ports:
      - "7777:7777/udp"
      - "7778:7778/udp"
      - "7779:7779/udp"
      - "7777:7777/tcp"
      - "7779:7779/tcp"
    volumes:
      - /mnt/user/appdata/steamcmd:/serverdata/steamcmd
      - /mnt/user/appdata/scum-server:/serverdata/SCUM
      - /mnt/user/appdata/scum-server/backups:/serverdata/backups
    restart: unless-stopped
